sfg.brewery.beer-service-host: http://localhost:8080

logging.level.guru: debug

server.port: 8081

spring:
    jackson:
        serialization:
            write-dates-as-timestamps: false
            write-date-timestamps-as-nanoseconds: false
    artemis:
        user: artemis
        password: simetraehcapa
    application:
        name: order-service

eureka:
    client:
        serviceUrl:
            #            default value
            defaultZone: http://localhost:8761/eureka
