sfg.brewery.beer-service-host: http://localhost:8080

logging.level.guru: debug

server.port: 8081

spring:
    application:
        name: order-service
    jackson:
        serialization:
            write-dates-as-timestamps: false
            write-date-timestamps-as-nanoseconds: false
    artemis:
        user: artemis
        password: simetraehcapa
    zipkin:
        enabled: false

eureka:
    client:
        serviceUrl:
            #            default value + 'netflix' is an username and 'eureka' is a password via base authentication
            defaultZone: http://netflix:eureka@localhost:8761/eureka
