sfg.brewery:
    beer-service-host: http://localhost:8080
    inventory-user: good
    inventory-password: beer

logging.level.guru: debug

server.port: 8081

spring:
    application:
        name: order-service
    jackson:
        serialization:
            write-dates-as-timestamps: false
            write-date-timestamps-as-nanoseconds: false
    artemis:
        user: artemis
        password: simetraehcapa
    zipkin:
        enabled: false
